=== CamPr0ngs/40260/xml/xml-00.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT direccion (nombrecompleto, correo, telefono, cumple)>
<!ELEMENT nombrecompleto (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT cumple (dia, mes ,anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== CamPr0ngs/40260/xml/xml-00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE direccion SYSTEM "xml-00.dtd""
<direccion>
    <nombrecompleto>
        <nombre>Camila</nombre>
        <apellidos>C Z</apellidos>
    </nombrecompleto>
    <correo>camila@gmail.com</correo>
    <telefono>2020202012</telefono>
    <cumple>
        <dia>20</dia>
        <mes>12</mes>
        <anio>2006</anio>
    </cumple>
</direccion>
